apiVersion: v1
kind: Namespace
metadata:
  name: "beta-corp"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "beta-corp-sa"
  namespace: "beta-corp"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: "beta-corp"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: "beta-corp"
subjects:
- kind: ServiceAccount
  name: "beta-corp-sa"
  namespace: "beta-corp"
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
