apiVersion: v1
kind: Namespace
metadata:
  name: "{{TENANT_NAME}}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{TENANT_NAME}}-sa"
  namespace: "{{TENANT_NAME}}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: "{{TENANT_NAME}}"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: "{{TENANT_NAME}}"
subjects:
- kind: ServiceAccount
  name: "{{TENANT_NAME}}-sa"
  namespace: "{{TENANT_NAME}}"
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
