apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-store
  namespace: "acme-corp"
spec:
  provider:
    gcpsm:
      projectID: "project-6e2b023f-2190-401a-aa7"
      # Authentic using the Pod's service account (Workload Identity)
      auth:
        workloadIdentity:
          clusterLocation: "us-central1-a"
          clusterName: "crego-shared-cluster"
          serviceAccountRef:
            name: "acme-corp-sa"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: "acme-corp"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-store
    kind: SecretStore
  target:
    name: tenant-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: "tenant-acme-corp-credentials"
        property: username
    - secretKey: password
      remoteRef:
        key: "tenant-acme-corp-credentials"
        property: password
    - secretKey: database
      remoteRef:
        key: "tenant-acme-corp-credentials"
        property: database
