apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-store
  namespace: "{{TENANT_NAME}}"
spec:
  provider:
    gcpsm:
      projectID: "{{PROJECT_ID}}"
      # Authentic using the Pod's service account (Workload Identity)
      auth:
        workloadIdentity:
          clusterLocation: "{{CLUSTER_LOCATION}}"
          clusterName: "{{CLUSTER_NAME}}"
          serviceAccountRef:
            name: "{{TENANT_NAME}}-sa"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: "{{TENANT_NAME}}"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-store
    kind: SecretStore
  target:
    name: tenant-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: "tenant-{{TENANT_NAME}}-credentials"
        property: username
    - secretKey: password
      remoteRef:
        key: "tenant-{{TENANT_NAME}}-credentials"
        property: password
    - secretKey: database
      remoteRef:
        key: "tenant-{{TENANT_NAME}}-credentials"
        property: database
