apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{TENANT_NAME}}-sa"
  namespace: "{{TENANT_NAME}}"
  annotations:
    # Workload Identity Annotation to bind GKE SA to GCP SA
    iam.gke.io/gcp-service-account: "sa-{{TENANT_NAME}}@{{PROJECT_ID}}.iam.gserviceaccount.com"
